name: 'Zeffo Environment Variables'
description: 'Outputs Zeffo environment variables'
inputs:
  tag:
    type: string
outputs:
  ref: ${{ steps.vars.outputs.ref }}
  environment: ${{ steps.vars.outputs.environment }}
  release_version: ${{ steps.vars.outputs.release_version }}
runs:
  using: 'composite'
  steps:
    - id: vars
      run: |
        REF=${{ github.ref }}
        TAG=${{ github.event.inputs.tag }}
        if test $TAG; then REF="refs/tags/$TAG"; fi
        ENVIRONMENT="develop"
        [[ $REF == refs/heads/release/* ]] && ENVIRONMENT="staging"
        [[ $REF == refs/tags/* ]] && ENVIRONMENT="production"
        RELEASE_VERSION=${{ github.sha }}
        if [[ $REF == refs/tags/* ]]; then
          REG='refs/tags/(.*)'
          [[ $REF =~ $REG ]]
          RELEASE_VERSION=${BASH_REMATCH[1]}
        fi
        echo "::set-output name=ref::${REF}"
        echo "::set-output name=environment::${ENVIRONMENT}"
        echo "::set-output name=release_version::${RELEASE_VERSION}"
