name: Embed Deploy

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      environment:
        required: true
        type: string
      release_version:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          echo ${{ inputs.ref }}
          echo ${{ inputs.environment }}
          echo ${{ inputs.release_version }}
