name: Zeffo Test

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      skipTests:
        type: boolean
        required: false
        default: false

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          echo ${{ inputs.skipTests }}

  test:
    runs-on: ubuntu-18.04
    if: ${{ ! inputs.skipTests }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      - run: |
          echo ${{ inputs.ref }}
          echo ${{ inputs.environment }}
          echo ${{ inputs.release_version }}
