name: Zeffo Test

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      skipTests:
        type: boolean
        required: false
        default: false

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: check skip test
        if: ${{ inputs.skipTests }}
        run: exit 0
      - run: |
          echo ${{ inputs.ref }}
          echo ${{ inputs.environment }}
          echo ${{ inputs.release_version }}
